project:
  type: website
  output-dir: docs
  resources:
  - "Sadhana R Sambandam CV.pdf"
website:
  title: 'Sadhana R Sambandam'
  favicon: S.svg
  navbar:
    logo: S4.svg
    text: Sadhana R Sambandam
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - blog.qmd
    search: true
  search:
      location: navbar
      type: overlay
  page-footer: 
    left: "Copyright 2025. Sadhana R Sambandam"

format:
  html:
    theme:
      - lux
      - styles.scss
    css: styles.css
    toc: false
    



