project:
  type: website

website:
  title: ''
  navbar:
    left:
      - href: index.qmd
        text: "<img src= 'C:/Users/sadha/OneDrive/Pictures/profile pic1.png' class='logo'>"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - blog.qmd

format:
  html:
    theme:
      - lux
      - styles.scss
    css: styles.css
    toc: true
    



