project:
  type: website

website:
  title: ''
  favicon: rocket-takeoff-dark.svg
  navbar:
    logo: rocket-takeoff.svg
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - blog.qmd
  page-footer: 
    left: "copyright 2025"

format:
  html:
    theme:
      - lux
      - styles.scss
    css: styles.css
    toc: false
    



