project:
  type: website

website:
  title: ''
  navbar:
    logo: profile_pic1.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - blog.qmd

format:
  html:
    theme:
      - lux
      - styles.scss
    css: styles.css
    toc: true
    



